# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='block',
            fields=[
                ('block_id', models.AutoField(serialize=False, primary_key=True)),
                ('user_id', models.CharField(max_length=30, null=True)),
                ('project_name', models.CharField(max_length=30, null=True)),
                ('session_name', models.CharField(max_length=30, null=True)),
                ('session_ver', models.IntegerField(default=0)),
                ('block_iden', models.CharField(max_length=20, null=True)),
                ('block_name', models.CharField(max_length=20, null=True)),
                ('block_ver', models.IntegerField(default=0)),
                ('parent_block_iden', models.CharField(max_length=20, null=True)),
                ('parent_block_ver', models.IntegerField(default=0)),
                ('clusterType', models.CharField(max_length=20, null=True)),
                ('clusterParam', models.CharField(max_length=20, null=True)),
                ('colors', models.CharField(max_length=50, null=True)),
                ('data', models.TextField()),
                ('last_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('creatation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('position_top', models.IntegerField(default=0)),
                ('position_left', models.IntegerField(default=0)),
                ('position_width', models.IntegerField(default=0)),
                ('position_height', models.IntegerField(default=0)),
                ('is_closed', models.BooleanField(default=False)),
                ('data_annotation', models.TextField(null=True)),
                ('data_name', models.CharField(max_length=40, null=True)),
                ('is_save', models.BooleanField(default=False)),
                ('save_ver', models.IntegerField(null=True, blank=True)),
                ('is_undo', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='block_annotation_history',
            fields=[
                ('annotation_id', models.AutoField(serialize=False, primary_key=True)),
                ('user_id', models.CharField(max_length=30, null=True)),
                ('project_name', models.CharField(max_length=30, null=True)),
                ('session_name', models.CharField(max_length=30, null=True)),
                ('session_ver', models.IntegerField(default=0)),
                ('block_iden', models.CharField(max_length=20, null=True)),
                ('block_ver', models.IntegerField(default=0)),
                ('research_annotation', models.TextField(null=True)),
                ('data_annotation', models.TextField(null=True)),
                ('author', models.CharField(max_length=30, null=True)),
                ('annotation_num', models.IntegerField(default=0)),
                ('is_removed', models.BooleanField(default=False)),
                ('last_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='closed_block',
            fields=[
                ('block_id', models.AutoField(serialize=False, primary_key=True)),
                ('user_id', models.CharField(max_length=30, null=True)),
                ('project_name', models.CharField(max_length=30, null=True)),
                ('session_name', models.CharField(max_length=30, null=True)),
                ('session_ver', models.IntegerField(default=0)),
                ('block_iden', models.CharField(max_length=20, null=True)),
                ('last_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='geromicsData',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, primary_key=True, auto_created=True)),
                ('GeneSymbol', models.CharField(max_length=100, null=True)),
                ('GSM1076965', models.CharField(max_length=100, null=True)),
                ('GSM1076966', models.CharField(max_length=100, null=True)),
                ('GSM1076967', models.CharField(max_length=100, null=True)),
                ('GSM1076968', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='go_obo',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, primary_key=True, auto_created=True)),
                ('pathway_id', models.CharField(max_length=30, null=True)),
                ('pathway_name', models.CharField(max_length=100, null=True)),
                ('pathway_namespace', models.CharField(max_length=100, null=True)),
                ('pathway_def', models.CharField(max_length=100, null=True)),
                ('pathway_synonym', models.CharField(max_length=100, null=True)),
                ('pathway_is_a', models.CharField(max_length=255, null=True)),
                ('pathway_alt_id', models.CharField(max_length=100, null=True)),
                ('pathway_subset', models.CharField(max_length=255, null=True)),
                ('pathway_xref', models.TextField(null=True)),
                ('pathway_comment', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='goa_human',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, primary_key=True, auto_created=True)),
                ('gene', models.CharField(max_length=30, null=True)),
                ('gene_ontology_pathway', models.CharField(max_length=100, null=True)),
                ('synonym_genes', models.CharField(max_length=100, null=True)),
                ('species', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='log_history',
            fields=[
                ('block_id', models.AutoField(serialize=False, primary_key=True)),
                ('scope', models.CharField(max_length=10, null=True)),
                ('action', models.CharField(max_length=30, null=True)),
                ('intent', models.CharField(max_length=30, null=True)),
                ('user_id', models.CharField(max_length=30, null=True)),
                ('project_name', models.CharField(max_length=30, null=True)),
                ('session_name', models.CharField(max_length=30, null=True)),
                ('session_ver', models.IntegerField()),
                ('block_iden', models.CharField(max_length=20, null=True)),
                ('block_name', models.CharField(max_length=20, null=True)),
                ('block_ver', models.IntegerField()),
                ('parent_block_iden', models.CharField(max_length=20, null=True)),
                ('parent_block_ver', models.IntegerField(default=0)),
                ('clusterType', models.CharField(max_length=20, null=True)),
                ('clusterParam', models.CharField(max_length=20, null=True)),
                ('colors', models.CharField(max_length=50, null=True)),
                ('data', models.TextField(null=True)),
                ('creatation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('position_top', models.IntegerField(null=True)),
                ('position_left', models.IntegerField(null=True)),
                ('position_width', models.IntegerField(null=True)),
                ('position_height', models.IntegerField(null=True)),
                ('is_action', models.BooleanField(default=False)),
                ('is_closed', models.BooleanField(default=False)),
                ('data_annotation', models.TextField(null=True)),
                ('data_name', models.CharField(max_length=40, null=True)),
                ('is_save', models.IntegerField(null=True, blank=True)),
                ('save_ver', models.IntegerField(null=True, blank=True)),
                ('is_new', models.BooleanField(default=False)),
                ('is_undo', models.IntegerField(null=True, blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='member',
            fields=[
                ('user_id', models.CharField(max_length=30, serialize=False, primary_key=True)),
                ('user_pw', models.CharField(max_length=30, null=True)),
                ('email', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('project_id', models.AutoField(serialize=False, primary_key=True)),
                ('project_name', models.CharField(max_length=30, null=True)),
                ('user_id', models.CharField(max_length=30)),
                ('last_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('project_annotation', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='session',
            fields=[
                ('session_id', models.AutoField(serialize=False, primary_key=True)),
                ('session_name', models.CharField(max_length=30, default='')),
                ('session_ver', models.IntegerField(default=0)),
                ('user_id', models.CharField(max_length=30, null=True)),
                ('project_name', models.CharField(max_length=30, null=True)),
                ('last_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('creatation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('parent_session_name', models.CharField(max_length=30, default='')),
                ('parent_session_ver', models.IntegerField(default=0)),
                ('branched_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('session_annotation', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='session_history',
            fields=[
                ('session_id', models.AutoField(serialize=False, primary_key=True)),
                ('session_name', models.CharField(max_length=30, default='')),
                ('session_ver', models.IntegerField(default=0)),
                ('user_id', models.CharField(max_length=30, null=True)),
                ('project_name', models.CharField(max_length=30, null=True)),
                ('last_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('block_list', models.CharField(max_length=255, null=True)),
                ('session_annotation', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='undo_block',
            fields=[
                ('block_id', models.AutoField(serialize=False, primary_key=True)),
                ('user_id', models.CharField(max_length=30, null=True)),
                ('project_name', models.CharField(max_length=30, null=True)),
                ('session_name', models.CharField(max_length=30, null=True)),
                ('session_ver', models.IntegerField(default=0)),
                ('block_iden', models.CharField(max_length=20, null=True)),
                ('block_name', models.CharField(max_length=20, null=True)),
                ('block_ver', models.IntegerField(default=0)),
                ('parent_block_iden', models.CharField(max_length=20, null=True)),
                ('parent_block_ver', models.IntegerField(default=0)),
                ('clusterType', models.CharField(max_length=20, null=True)),
                ('clusterParam', models.CharField(max_length=20, null=True)),
                ('colors', models.CharField(max_length=50, null=True)),
                ('data', models.TextField()),
                ('last_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('position_top', models.IntegerField(null=True)),
                ('position_left', models.IntegerField(null=True)),
                ('position_width', models.IntegerField(null=True)),
                ('position_height', models.IntegerField(null=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('data_annotation', models.TextField(null=True)),
                ('data_name', models.CharField(max_length=40, null=True)),
                ('is_save', models.BooleanField(default=False)),
                ('save_ver', models.IntegerField(null=True, blank=True)),
                ('action', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
