from django.conf import settings
from django.conf.urls import url, include
from . import views, projects, sessions, units, sankey, members, recAlgo, graph, gsea, answer, analysis #prevSys

urlpatterns = [

    url(r'^goobo.html$', views.goobo, name='goobo'),
    url(r'^kegg.html$', views.kegg, name='kegg'),
    url(r'^david.html$', views.david, name='david'),

    url(r'^clusterList.html/$', views.cluster_list, name='clusterList'),
    url(r'^$', views.index, name='index'),
    url(r'^userStudy.html$', views.user_study, name='user_study'),
    url(r'^sankeyList.html$', views.sankey_list, name='sankey_list'),
    url(r'^static/(?P<filename>\w+.*)$', views.file_name_download, name='fileNameDownload'),
    url(r'^clusterList.html/$', views.cluster_list, name='clusterList'),
    url(r'^clusters.html$', units.clusters, name='clusters'),
    url(r'^login.html$', members.login, name='login'),
    url(r'^logout.html$', members.logout, name='logout'),
    url(r'^register.html$', members.register, name='register'),
    url(r'^createProject.html$', projects.create_project, name='create_project'),
    url(r'^deleteProject.html$', projects.delete_project, name='delete_project'),
    url(r'^getProjects.html$', projects.get_projects, name='get_projects'),
    url(r'^newSession.html$', sessions.create_session, name='create_session'),
    url(r'^delSession.html$', sessions.delete_session, name='delete_session'),
    url(r'^getSession.html$', sessions.get_session, name='get_session'),
    url(r'^registerTest.html$', members.registerTest, name='registerTest'),
    url(r'^getBlocks.html$', units.get_blocks, name='get_blocks'),
    url(r'^saveSession.html$', sessions.save_session, name='save_session'),
    url(r'^updateSessionAnnotation.html$', sessions.update_session_annotation, name='update_session_annotation'),
    url(r'^branchSession.html$', sessions.branch_session, name='branch_session'),
    url(r'^closeBlock.html$', units.close_block, name='close_block'),
    url(r'^getSessionHistory.html$', sankey.get_session_history, name='get_session_history'),
    url(r'^insertLog.html$', views.insert_log, name='insert_log'),
    url(r'^fromToSession.html$', sankey.from_to_session, name='from_to_session'),
    url(r'^createBlockAnnotation.html$', units.create_block_annotation, name='create_block_annotation'),
    url(r'^deleteBlockAnnotation.html$', units.delete_block_annotation, name='delete_block_annotation'),
    url(r'^updateBlockAnnotation.html$', units.update_block_annotation, name='update_block_annotation'),
    url(r'^actionHistory.html$', sankey.action_history, name='action_history'),
    url(r'^goaHuman.html$', views.goaHuman, name='goaHuman'),
    url(r'^seminar.html$', views.seminar, name='seminar'),
    url(r'^restoration.html$', units.restoration, name='restoration'),
    url(r'^map.html$', views.map, name='map'),
    url(r'^uitest.html$', views.uitest, name='uitest'),
    url(r'^color.html$', views.color, name='color'),
    url(r'^daehwa.html$', views.daehwa, name='daehwa'),
    url(r'^fromToUnit.html$', sankey.from_to_unit, name='from_to_unit'),
    url(r'^chkPrevSes.html$', sessions.check_preview_session, name='check_preview_session'),
    url(r'^depenCheck.html$', units.depen_check, name='depen_check'),
    url(r'^undoAction.html$', units.undo_action, name='undo_action'),
    url(r'^redoAction.html$', units.redo_action, name='redo_action'),
    url(r'^actionMove.html$', sankey.action_move, name='action_move'),
    url(r'^unitCopy.html$', sankey.unit_copy, name='unit_copy'),
    url(r'^visTypes.html$', views.vis_types, name='unit_copy'),
    url(r'^recAlgo.html$', recAlgo.recommendation, name='recommendation'),
    url(r'^graph.html$', graph.network, name='network'),
    url(r'^gsea.html$', gsea.make_gsea, name='gsea'),
    url(r'^unavUndo.html$', views.unav_undo, name='unav_undo'),
    url(r'^species.html$', views.species, name='species'),
    url(r'^bookmark.html$', sankey.bookmark, name='bookmark'),
    url(r'^adminPage.html$', views.adminPage, name='adminPage'),
    url(r'^getMembers.html$', members.get_members, name='getMembers'),
    url(r'^makeMembers.html$', members.make_members, name='makeMembers'),
    url(r'^delMembers.html$', members.del_members, name='delMembers'),
    url(r'^delBookmark.html$', sankey.delete_bookmark, name='delete_bookmark'),
    url(r'^answer.html$', answer.get_answer, name='answer'),
    url(r'^answer2.html$', answer.get_second_answer, name='answer2'),
    url(r'^analysis.html$', analysis.get_analysis, name='analysis'),
    url(r'^setFirst.html$', sankey.set_first, name='setFirst'),
]
